{
 "title": "EV",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "old",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "OLD Puissance de charge instantanée (A)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "charging_instant_power", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "OLD Batt %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "sum(battery_Level)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "(De)charge (Kw) (depuis %) lissé sur 30min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(vin) (deriv(battery_Level[30m]) * 0.6 * 3600)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "(De)charge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Batt %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sum by(vin) (ev_battery_Level)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Puissance de charge instantanée (A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "min by(vin) (ev_charging_instant_power)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(De)charge (Kw) (depuis %) lissé sur 6/15min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum by(vin) (deriv(ev_battery_Level[6m]) * 0.6 * 3600), \"interval\", \"6m\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by(vin) (deriv(ev_battery_Level[15m]) * 0.6 * 3600), \"interval\", \"15m\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plug/Charge Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "sum by(vin) (ev_plug_status)", "legendFormat": "__auto" },
    {
     "expr": "sum by(vin) (ev_charging_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INOP Rate Available KWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(vin) (rate(ev_battery_Available_Energy[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "MileAge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum by(vin) (ev_total_Mileage)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batt KWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum by(vin) (ev_battery_Available_Energy)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Autonomie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Autonomie",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "expr": "sum by(vin) (ev_battery_Autonomy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conso ODB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 50 },
   "targets": [
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  }
 ]
}